function testingMAIN()
    fig = figure('Name', 'Digital Communication System - HMI', ...
                 'Position', [500, 400, 600, 400], ...
                 'Color', [0.95 0.95 0.95], ...
                 'MenuBar', 'none', ...
                 'NumberTitle', 'off', ...
                 'Resize', 'off');
    uicontrol('Style', 'text', ...
              'Position', [50, 330, 500, 40], ...
              'String', 'Digital Communication System', ...
              'FontSize', 18, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.95 0.95 0.95], ...
              'ForegroundColor', [0.2 0.2 0.8]);
    uicontrol('Style', 'text', ...
              'Position', [50, 300, 500, 25], ...
              'String', ' Digital Communication project with Multiple Line Coding Techniques', ...
              'FontSize', 11, ...
              'BackgroundColor', [0.95 0.95 0.95], ...
              'ForegroundColor', [0.4 0.4 0.4]);
    uicontrol('Style', 'text', ...
              'Position', [50, 240, 500, 50], ...
              'String', {'  MADE BY : SEIF AHMED & ABDELHAMEED AHMED '}, ...
              'FontSize', 15, ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'normal');
    uicontrol('Style', 'pushbutton', ...
              'Position', [100, 170, 180, 50], ...
              'String', ' Launch Transmitter', ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.3 0.7 0.3], ...
              'ForegroundColor', 'white', ...
              'Callback', @(src, evt) launchTransmitter());
    uicontrol('Style', 'pushbutton', ...
              'Position', [320, 170, 180, 50], ...
              'String', ' Launch Receiver', ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.3 0.5 0.8], ...
              'ForegroundColor', 'white', ...
              'Callback', @(src, evt) launchReceiver());
    uicontrol('Style', 'pushbutton', ...
              'Position', [150, 100, 300, 50], ...
              'String', 'Launch Both Systems', ...
              'FontSize', 13, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.8 0.3 0.3], ...
              'ForegroundColor', 'white', ...
              'Callback', @(src, evt) launchBoth());
    statusText = uicontrol('Style', 'text', ...
                          'Position', [50, 50, 500, 30], ...
                          'String', 'Ready to launch...', ...
                          'FontSize', 10, ...
                          'BackgroundColor', [0.95 0.95 0.95], ...
                          'ForegroundColor', [0 0.5 0], ...
                          'Tag', 'StatusText');
    uicontrol('Style', 'pushbutton', ...
              'Position', [250, 10, 100, 30], ...
              'String', 'Close All', ...
              'FontSize', 10, ...
              'Callback', @(src, evt) closeAll());
    function launchTransmitter()
        try
            Testing_TX();
            set(statusText, 'String', ' Transmitter launched successfully!', ...
                'ForegroundColor', [0 0.5 0]);
        catch ME
            set(statusText, 'String', [' Error: ' ME.message], ...
                'ForegroundColor', [0.8 0 0]);
        end
    end
    function launchReceiver()
        try
            Testing_RX();
            set(statusText, 'String', 'Receiver launched successfully!', ...
                'ForegroundColor', [0 0.5 0]);
        catch ME
            set(statusText, 'String', [' Error: ' ME.message], ...
                'ForegroundColor', [0.8 0 0]);
        end
    end
    function launchBoth()
        try
            evalin('base', 'clear transmitted_data');
            % Launch transmitter (positioned on left)
            Testing_TX();
            tx_fig = gcf;
            set(tx_fig, 'Position', [50, 100, 1400, 850]);  
            pause(0.5); 
            % Launch receiver (positioned on right)
            Testing_RX();
            rx_fig = gcf;
            set(rx_fig, 'Position', [1500, 100, 1400, 850]);
            set(statusText, 'String', ' Both systems launched! Start with Transmitter.', ...
                'ForegroundColor', [0 0.5 0]);
        catch ME
            set(statusText, 'String', [' Error: ' ME.message], ...
                'ForegroundColor', [0.8 0 0]);
        end
    end
    function closeAll()
        % Close all figure windows
        close all;
        evalin('base', 'clear transmitted_data', '');
    end
end